import { useState, useEffect } from "react";

// ── NAMES ── swap this array with your real guest list ──
const NAMES = [
  "Jack Aarons","Dina Barrish","Cristina Bernal","Lauren Bickel",
  "Lilah Brown","Katelyn Cao","Trey Carrillo","Chloe Chin",
  "Emily Clark","Brian Davids","Elisabeth Engelson","Elena Faulise",
  "Marian Fernandez Alonso","Paola Garcia","Gabriella Gimson",
  "Camille Girardeau-Montau","Jimena Gonzalez Palma","Anya Gowda",
  "Paige Gross","Lynn Hamamji","Karis Harvey","Ashley Holcomb",
  "Maurice Holden","Shahid Hossain","Jack Hutton","Brett Hyman",
  "Lila Josey","Amanda Kamp","Natalie Kang","Gloria Kim",
  "Elizabeth Liston","Macey Marketos","Natalie Massaed",
  "Amelia McConnico","Olivia McMurray","Ally Mitchell",
  "Michaela Mithoff","Lauren Moak","Abrianna Morales",
  "Jonathan Moreno-Cedillo","Ayanna Moten","Julie Nguyen",
  "Bertha Palma","Shristi Patni","Namah Rakesh Kohli","Erin Rand",
  "Alex Roeder","Sydney Rude","Kory Sarfo","Audrey Schultz",
  "Jitesh Sharma","Patricia Sharon","Farrah Skorman","Justin Small",
  "Rivers Solis","Caroline Sumner","Simi Thakur","Alley Tran",
  "Syed Usama Uzair","Gladys Del R Velarde Cava","Vanessa Villarreal",
  "Rylee Vines","Elise Walsh","Cameron Worden","Sabina Zeynalova"
];

const ACCENT_COLORS = [
  "#FF6B6B","#4ECDC4","#FFE66D","#A78BFA","#F97316",
  "#06D6A0","#FF477E","#00B4D8","#E9FF70","#C084FC"
];

function generateBashScript(name) {
  return [
    '# TERMINAL PARTY for ' + name,
    '# Paste this entire block into your terminal and hit Enter.',
    '# Works on macOS (zsh or bash), iTerm2, any Linux terminal.',
    '# Make it FULLSCREEN for the best experience!',
    '# Ctrl+C to exit anytime.',
    'bash << \'PARTY\'',
    'NAME="' + name + '"',
    'UPPER=$(echo "$NAME" | tr \'[:lower:]\' \'[:upper:]\')',
    '',
    'trap \'tput cnorm; tput sgr0; clear; exit\' INT TERM EXIT',
    'tput civis; clear',
    'COLS=$(tput cols); LNS=$(tput lines)',
    'MX=$((COLS/2)); MY=$((LNS/2))',
    '',
    '# colors',
    'R=\'\\033[91m\'; G=\'\\033[92m\'; Y=\'\\033[93m\'; B=\'\\033[94m\'',
    'M=\'\\033[95m\'; C=\'\\033[96m\'; W=\'\\033[97m\'',
    'dG=\'\\033[32m\'; dC=\'\\033[36m\'',
    'BO=\'\\033[38;5;208m\'',
    'BD=\'\\033[1m\'; DM=\'\\033[2m\'; RS=\'\\033[0m\'',
    'CL=("$R" "$G" "$Y" "$B" "$M" "$C" "$W")',
    '',
    'cur(){ printf "\\033[%d;%dH" "$1" "$2"; }',
    'out(){ printf "%b" "$@"; }',
    '',
    '# shared character arrays (used across multiple phases)',
    'FW=(\'*\' \'+\' \'o\' \'.\' \'x\' \'~\')',
    'EXP_CHARS=("*" "#" "@" "!" "%" "X" "+" "~" "^" "&")',
    '',
    '# block letter font (5 rows, | separated)',
    'font_data() {',
    '  case "$1" in',
    '    A) echo " ### |#   #|#####|#   #|#   #";;',
    '    B) echo "#### |#   #|#### |#   #|#### ";;',
    '    C) echo " ####|#    |#    |#    | ####";;',
    '    D) echo "#### |#   #|#   #|#   #|#### ";;',
    '    E) echo "#####|#    |###  |#    |#####";;',
    '    F) echo "#####|#    |###  |#    |#    ";;',
    '    G) echo " ####|#    |# ###|#   #| ####";;',
    '    H) echo "#   #|#   #|#####|#   #|#   #";;',
    '    I) echo "###| # | # | # |###";;',
    '    J) echo " ####|    #|    #|#   #| ### ";;',
    '    K) echo "#  # |# #  |##   |# #  |#  # ";;',
    '    L) echo "#    |#    |#    |#    |#####";;',
    '    M) echo "#   #|## ##|# # #|#   #|#   #";;',
    '    N) echo "#   #|##  #|# # #|#  ##|#   #";;',
    '    O) echo " ### |#   #|#   #|#   #| ### ";;',
    '    P) echo "#### |#   #|#### |#    |#    ";;',
    '    Q) echo " ### |#   #|# # #|#  # | ## #";;',
    '    R) echo "#### |#   #|#### |# #  |#   #";;',
    '    S) echo " ####|#    | ### |    #|#### ";;',
    '    T) echo "#####|  #  |  #  |  #  |  #  ";;',
    '    U) echo "#   #|#   #|#   #|#   #| ### ";;',
    '    V) echo "#   #|#   #| # # | # # |  #  ";;',
    '    W) echo "#   #|#   #|# # #|## ##|#   #";;',
    '    X) echo "#   #| # # |  #  | # # |#   #";;',
    '    Y) echo "#   #| # # |  #  |  #  |  #  ";;',
    '    Z) echo "#####|   # |  #  | #   |#####";;',
    '    *) echo "     |     |     |     |     ";;',
    '  esac',
    '}',
    'font_width() { local d; d=$(font_data "$1"); local f="${d%%|*}"; echo ${#f}; }',
    '',
    '# calc name dimensions',
    'TOTAL_W=0',
    'for ((i=0;i<${#UPPER};i++)); do',
    '  w=$(font_width "${UPPER:$i:1}"); TOTAL_W=$((TOTAL_W+w+2))',
    'done',
    'SX=$(( (COLS-TOTAL_W)/2 )); ((SX<1)) && SX=1',
    'SY=$(( (LNS-5)/2 ))',
    '',
    '# draw one block letter at arbitrary y',
    'draw_letter_at() {',
    '  local letter=$1 cx=$2 by=$3 mode=$4 color=$5',
    '  local data row_data',
    '  local SC=(\'#\' \'@\' \'%\' \'&\' \'?\' \'!\' \'>\' \'<\' \'~\' \'^\' \'*\')',
    '  data=$(font_data "$letter")',
    '  IFS=\'|\' read -ra rows <<< "$data"',
    '  for ((rw=0;rw<5;rw++)); do',
    '    cur $((by+rw)) $cx',
    '    row_data="${rows[$rw]}"',
    '    for ((ch=0;ch<${#row_data};ch++)); do',
    '      if [ "${row_data:$ch:1}" = "#" ]; then',
    '        if [ "$mode" = "solid" ]; then',
    '          out "${BD}${color}#${RS}"',
    '        else',
    '          out "${BD}${color}${SC[$((RANDOM%${#SC[@]}))]}${RS}"',
    '        fi',
    '      else',
    '        out " "',
    '      fi',
    '    done',
    '  done',
    '}',
    'draw_letter() { draw_letter_at "$1" "$2" "$SY" "$3" "$4"; }',
    '',
    '# ═══════════════════════════════════════════════════',
    '# PHASE 1: STARS WAKING UP',
    '# ═══════════════════════════════════════════════════',
    '# Fade in: dim dots appear slowly',
    'TWINKLE=("." "," "~" ":" ";")',
    'for ((i=0;i<50;i++)); do',
    '  cur $((RANDOM%LNS+1)) $((RANDOM%COLS+1))',
    '  out "${DM}${CL[$((RANDOM%7))]}${TWINKLE[$((RANDOM%${#TWINKLE[@]}))]}${RS}"',
    '  sleep 0.025',
    'done',
    '# Brighter dots layer in',
    'for ((i=0;i<80;i++)); do',
    '  cur $((RANDOM%LNS+1)) $((RANDOM%COLS+1))',
    '  out "${DM}${CL[$((RANDOM%7))]}.${RS}"',
    '  sleep 0.012',
    'done',
    '# Twinkle: random stars flash bright then dim',
    'for ((tw=0;tw<3;tw++)); do',
    '  for ((i=0;i<20;i++)); do',
    '    tx=$((RANDOM%COLS+1)); ty=$((RANDOM%LNS+1))',
    '    cur $ty $tx; out "${BD}${CL[$((RANDOM%7))]}*${RS}"',
    '    sleep 0.02',
    '  done',
    '  for ((i=0;i<10;i++)); do',
    '    tx=$((RANDOM%COLS+1)); ty=$((RANDOM%LNS+1))',
    '    cur $ty $tx; out "${DM}${CL[$((RANDOM%7))]}.${RS}"',
    '    sleep 0.01',
    '  done',
    'done',
    '# Final bright stars',
    'for ((i=0;i<40;i++)); do',
    '  cur $((RANDOM%LNS+1)) $((RANDOM%COLS+1))',
    '  out "${BD}${CL[$((RANDOM%7))]}*${RS}"',
    '  sleep 0.015',
    'done',
    'sleep 0.4; clear',
    '',
    '# ═══════════════════════════════════════════════════',
    '# PHASE 2: UT MATRIX RAIN',
    '# ═══════════════════════════════════════════════════',
    'UT_WORDS=("LONGHORN" "HOOKEM" "MCCOMBS" "AUSTIN" "TOWER" "BEVO" "TEXAS" "BURNT" "ORANGE" "MARKETING" "2026" "MASTERS" "PCL" "GUADALUPE" "DRAG" "SPEEDWAY" "JESTER" "DARRELL" "ROYAL" "40ACRES" "WHATSTARTSHERE" "HOOK" "EM" "HORNS" "SLAY" "GOAT" "CLASS" "GRAD" "McCombs" "DEGREE" "PARTY" "WOOO" "LETS" "GO")',
    'NAME_WORDS=()',
    'for word in $UPPER; do NAME_WORDS+=("$word"); done',
    'ALL_RAIN=("${UT_WORDS[@]}" "${NAME_WORDS[@]}" "${UT_WORDS[@]}" "${UT_WORDS[@]}")',
    '',
    'declare -a sr_x sr_y sr_sp sr_word sr_pos sr_color',
    'SR_N=24',
    'for ((i=0;i<SR_N;i++)); do',
    '  sr_x[$i]=$((RANDOM%COLS+1))',
    '  sr_y[$i]=$((-(RANDOM%10)))',
    '  sr_sp[$i]=$((RANDOM%2+1))',
    '  sr_word[$i]="${ALL_RAIN[$((RANDOM%${#ALL_RAIN[@]}))]}"',
    '  sr_pos[$i]=0',
    '  sr_color[$i]=$((RANDOM%3))',
    'done',
    '',
    'for ((f=0;f<90;f++)); do',
    '  for ((i=0;i<SR_N;i++)); do',
    '    oy=${sr_y[$i]}; ox=${sr_x[$i]}',
    '    word="${sr_word[$i]}"',
    '    pos=${sr_pos[$i]}',
    '    ey=$((oy-2))',
    '    ((ey>0 && ey<=LNS && ox>0 && ox<=COLS)) && { cur $ey $ox; out " "; }',
    '    sr_y[$i]=$((oy + sr_sp[$i]))',
    '    ny=${sr_y[$i]}',
    '    if ((pos >= ${#word})); then',
    '      sr_y[$i]=$((-(RANDOM%8)))',
    '      sr_x[$i]=$((RANDOM%COLS+1))',
    '      sr_word[$i]="${ALL_RAIN[$((RANDOM%${#ALL_RAIN[@]}))]}"',
    '      sr_pos[$i]=0',
    '      sr_color[$i]=$((RANDOM%3))',
    '      continue',
    '    fi',
    '    ch="${word:$pos:1}"',
    '    sr_pos[$i]=$((pos+1))',
    '    cc=${sr_color[$i]}',
    '    if ((cc==0)); then hc="${G}"; tc="${dG}";',
    '    elif ((cc==1)); then hc="${BO}"; tc="${Y}";',
    '    else hc="${C}"; tc="${B}"; fi',
    '    ((ny>0 && ny<=LNS && ox>0 && ox<=COLS)) && { cur $ny $ox; out "${BD}${hc}${ch}${RS}"; }',
    '    ty=$((ny-1))',
    '    ((ty>0 && ty<=LNS && ox>0 && ox<=COLS)) && { cur $ty $ox; out "${tc}${ch}${RS}"; }',
    '    ((ny>LNS)) && {',
    '      sr_y[$i]=$((-(RANDOM%6)))',
    '      sr_x[$i]=$((RANDOM%COLS+1))',
    '      sr_word[$i]="${ALL_RAIN[$((RANDOM%${#ALL_RAIN[@]}))]}"',
    '      sr_pos[$i]=0',
    '      sr_color[$i]=$((RANDOM%3))',
    '    }',
    '  done',
    '  sleep 0.035',
    'done',
    'sleep 0.2; clear',
    '',
    '# ═══════════════════════════════════════════════════',
    '# PHASE 3: MATRIX HEX FLOOD (wave from center outward)',
    '# ═══════════════════════════════════════════════════',
    'HX=("0" "1" "A" "B" "C" "D" "E" "F" "0" "1" "2" "3" "4" "5" "6" "7" "8" "9")',
    'HEX_COLORS=("${G}" "${dG}" "${C}" "${dC}")',
    '# Wave outward from center: ring by ring',
    'for ((ring=0;ring<=MX;ring+=2)); do',
    '  for ((attempts=0;attempts<ring*3+4;attempts++)); do',
    '    # Pick random point at approximately this ring distance',
    '    angle=$((RANDOM%360))',
    '    rx=$((MX + (ring * (RANDOM%3-1+1)) * (2*(angle%2)-1) / 2 ))',
    '    ry=$((MY + (ring/2) * (2*((angle/90)%2)-1) ))',
    '    ((rx<1)) && rx=1; ((rx>COLS)) && rx=$COLS',
    '    ((ry<1)) && ry=1; ((ry>LNS)) && ry=$LNS',
    '    hc="${HEX_COLORS[$((RANDOM%4))]}"',
    '    cur $ry $rx; out "${hc}${HX[$((RANDOM%${#HX[@]}))]}${RS}"',
    '  done',
    '  sleep 0.008',
    'done',
    '# Fill any remaining gaps',
    'for ((y=1;y<=LNS;y++)); do',
    '  for ((x=1;x<=COLS;x+=3)); do',
    '    cur $y $x; out "${G}${HX[$((RANDOM%${#HX[@]}))]}${RS}"',
    '  done',
    'done',
    'sleep 0.4',
    '# Fade out in waves from edges inward',
    'for ((ring=MX;ring>=0;ring-=3)); do',
    '  for ((i=0;i<$((COLS*LNS/12));i++)); do',
    '    fx=$((RANDOM%COLS+1)); fy=$((RANDOM%LNS+1))',
    '    dist=$(( (fx-MX)*(fx-MX)/4 + (fy-MY)*(fy-MY) ))',
    '    limit=$((ring*ring/4))',
    '    ((dist>=limit)) && { cur $fy $fx; out " "; }',
    '  done',
    '  sleep 0.03',
    'done',
    'sleep 0.1; clear',
    '',
    '# ═══════════════════════════════════════════════════',
    '# PHASE 3.5: SCREEN GLITCH (chaos flicker)',
    '# ═══════════════════════════════════════════════════',
    'GL=("E" "R" "R" "O" "R" " " "?" "!" "#" "@" "%" "&" "/" "\\\\" "|" "~")',
    'for ((glitch=0;glitch<3;glitch++)); do',
    '  for ((gy=1;gy<=LNS;gy+=2)); do',
    '    cur $gy 1; buf=""',
    '    for ((gx=1;gx<=COLS;gx++)); do',
    '      buf+="${GL[$((RANDOM%${#GL[@]}))]}"',
    '    done',
    '    out "${BD}${CL[$((RANDOM%7))]}${buf}${RS}"',
    '  done',
    '  sleep 0.04',
    '  # "shift" — redraw offset lines',
    '  for ((gy=2;gy<=LNS;gy+=2)); do',
    '    cur $gy 1; buf=""',
    '    for ((gx=1;gx<=COLS;gx++)); do',
    '      buf+="${GL[$((RANDOM%${#GL[@]}))]}"',
    '    done',
    '    out "${DM}${CL[$((RANDOM%7))]}${buf}${RS}"',
    '  done',
    '  sleep 0.03',
    'done',
    '# flash black/white',
    'for ((zz=0;zz<2;zz++)); do',
    '  clear; sleep 0.04',
    '  for ((gy=1;gy<=LNS;gy++)); do',
    '    cur $gy 1; printf "%*s" "$COLS" "" | tr " " "#"',
    '  done',
    '  sleep 0.03',
    'done',
    'clear',
    '',
    '# ═══════════════════════════════════════════════════',
    '# DISCO FLOOR',
    '# ═══════════════════════════════════════════════════',
    '# Disco ball at top center',
    'DB_X=$((MX-6))',
    'DB=(',
    '"     .----.     "',
    '"   / o  o  \\\\   "',
    '"  | o  o  o |  "',
    '"   \\\\ o  o  /   "',
    '"     ----      "',
    '"      ||       "',
    ')',
    'for ((bl=0;bl<${#DB[@]};bl++)); do',
    '  cur $((1+bl)) $DB_X; out "${BD}${W}${DB[$bl]}${RS}"',
    'done',
    '',
    '# Light rays from disco ball',
    'for ((ray=0;ray<12;ray++)); do',
    '  rx=$((MX + (ray-6)*6 + RANDOM%3))',
    '  for ((ry=7;ry<7+ray%4+2;ry++)); do',
    '    ((rx>0 && rx<=COLS && ry>0 && ry<=LNS)) && {',
    '      cur $ry $rx; out "${DM}${CL[$((RANDOM%7))]}|${RS}"',
    '    }',
    '  done',
    'done',
    'sleep 0.2',
    '',
    '# Animated checkerboard dance floor with colored tiles',
    'DBLK=("█" "▓" "▒" "░")',
    'DCL=("\\033[41m" "\\033[42m" "\\033[43m" "\\033[44m" "\\033[45m" "\\033[46m" "\\033[47m")',
    'FLOOR_TOP=$((LNS/2))',
    'for ((disco=0;disco<24;disco++)); do',
    '  # Redraw disco ball sparkle',
    '  cur 1 $DB_X',
    '  if ((disco%3==0)); then out "${BD}${Y}     .----.     ${RS}"',
    '  elif ((disco%3==1)); then out "${BD}${W}     .----.     ${RS}"',
    '  else out "${BD}${C}     .----.     ${RS}"; fi',
    '',
    '  # Draw checkerboard floor tiles',
    '  for ((dy=FLOOR_TOP;dy<=LNS;dy++)); do',
    '    cur $dy 1; buf=""',
    '    for ((dx=1;dx<=COLS;dx++)); do',
    '      if (( (dx/3+dy+disco)%2==0 )); then',
    '        buf+="${DBLK[$((disco%${#DBLK[@]}))]}"',
    '      else',
    '        buf+=" "',
    '      fi',
    '    done',
    '    out "${DCL[$(( (dy+disco)%7 ))]}${buf}${RS}"',
    '  done',
    '',
    '  # Spotlights sweep across',
    '  spot=$((MX + (disco%8-4)*8))',
    '  for ((sy=8;sy<FLOOR_TOP;sy++)); do',
    '    ((spot>0 && spot<=COLS && sy>0 && sy<=LNS)) && {',
    '      cur $sy $spot; out "${BD}${CL[$((disco%7))]}|${RS}"',
    '    }',
    '  done',
    '  sleep 0.06',
    'done',
    'sleep 0.3; clear',
    '',
    '# ═══════════════════════════════════════════════════',
    '# R vs PYTHON WAR',
    '# ═══════════════════════════════════════════════════',
    'R_ART=(',
    '"  ____  "',
    '" |  _ \\\\ "',
    '" | |_) |"',
    '" |  _ < "',
    '" |_| \\\\_\\\\"',
    ')',
    'R_H=5; R_W=9',
    '',
    'PY_ART=(',
    '" _____  "',
    '"|  __ \\\\ "',
    '"| |__) |"',
    '"|  ___/ "',
    '"|_|     "',
    ')',
    'PY_H=5; PY_W=9',
    '',
    '# Snake for Python side',
    'PY_SNAKE=("~~~~~>" "~~~~>" "~~~>" "~~>" "~>" ">" "~>" "~~>" "~~~>" "~~~~>")',
    '# Stats for R side',
    'R_STATS=("mean()" "lm()" "ggplot" "dplyr" "t.test" "cor()")',
    '',
    'FIGHT_Y=$((MY - 3))',
    '',
    '# Pre-fight: titles appear',
    'PY_TITLE=">>> PYTHON <<<"',
    'R_TITLE=">>> R <<<"',
    'PY_TX=$(( COLS/4 - ${#PY_TITLE}/2 ))',
    'R_TX=$(( 3*COLS/4 - ${#R_TITLE}/2 ))',
    'cur $((FIGHT_Y-3)) $PY_TX; out "${BD}${B}${PY_TITLE}${RS}"',
    'cur $((FIGHT_Y-3)) $R_TX; out "${BD}${C}${R_TITLE}${RS}"',
    'sleep 0.3',
    '',
    '# Charge toward each other with projectiles',
    'for ((step=0;step<=MX-6;step+=2)); do',
    '  py_x=$((step+1))',
    '  r_x=$((COLS-step-R_W))',
    '  # Clear & draw Python',
    '  for ((ll=0;ll<PY_H;ll++)); do',
    '    cur $((FIGHT_Y+ll)) $py_x; out "         "',
    '    cur $((FIGHT_Y+ll)) $py_x; out "${BD}${B}${PY_ART[$ll]}${RS}"',
    '  done',
    '  # Clear & draw R',
    '  for ((ll=0;ll<R_H;ll++)); do',
    '    cur $((FIGHT_Y+ll)) $r_x; out "         "',
    '    cur $((FIGHT_Y+ll)) $r_x; out "${BD}${C}${R_ART[$ll]}${RS}"',
    '  done',
    '  # Python shoots snake projectiles',
    '  ((step%6==0)) && {',
    '    sn="${PY_SNAKE[$((RANDOM%${#PY_SNAKE[@]}))]}"',
    '    sl_y=$((FIGHT_Y+RANDOM%PY_H))',
    '    cur $sl_y $((py_x+PY_W)); out "${BD}${G}${sn}${RS}"',
    '  }',
    '  # R shoots function projectiles',
    '  ((step%8==0)) && {',
    '    rf="${R_STATS[$((RANDOM%${#R_STATS[@]}))]}"',
    '    sl_y=$((FIGHT_Y+RANDOM%R_H))',
    '    ((r_x>3)) && { cur $sl_y $((r_x-${#rf}-1)); out "${BD}${M}${rf}${RS}"; }',
    '  }',
    '  # VS text appears midway',
    '  ((step>MX/3)) && {',
    '    cur $((FIGHT_Y+2)) $((MX-2))',
    '    if ((step%4<2)); then out "${BD}${R} VS ${RS}"; else out "${BD}${Y} VS ${RS}"; fi',
    '  }',
    '  # Battle sparks around center',
    '  ((step>MX/2)) && {',
    '    for ss in 1 2 3; do',
    '      sx=$((MX+RANDOM%10-5)); sy=$((FIGHT_Y+RANDOM%5))',
    '      ((sx>0 && sx<=COLS && sy>0 && sy<=LNS)) && {',
    '        cur $sy $sx; out "${BD}${CL[$((RANDOM%7))]}${EXP_CHARS[$((RANDOM%${#EXP_CHARS[@]}))]}${RS}"',
    '      }',
    '    done',
    '  }',
    '  sleep 0.02',
    'done',
    '',
    '# COLLISION EXPLOSION',
    'for ((er=1;er<=15;er++)); do',
    '  for ((angle=0;angle<24;angle++)); do',
    '    rad_x=$(( (angle%5-2) * er ))',
    '    rad_y=$(( (angle/5-2) * er / 2 ))',
    '    ex=$((MX+rad_x)); ey=$((FIGHT_Y+2+rad_y))',
    '    ((ex>0 && ex<=COLS && ey>0 && ey<=LNS)) && {',
    '      cur $ey $ex',
    '      out "${BD}${CL[$((RANDOM%7))]}${EXP_CHARS[$((RANDOM%${#EXP_CHARS[@]}))]}${RS}"',
    '    }',
    '  done',
    '  sleep 0.025',
    'done',
    '',
    '# Screen flash',
    'sleep 0.1; clear; sleep 0.05',
    'for ((gy=1;gy<=LNS;gy++)); do',
    '  cur $gy 1; printf "%*s" "$COLS" "" | tr " " "#"',
    'done',
    'sleep 0.05; clear',
    '',
    '# Result: just the name centered',
    'WIN_X=$(( (COLS-${#UPPER})/2 ))',
    'cur $MY $WIN_X',
    'for ((wi=0;wi<${#UPPER};wi++)); do',
    '  out "${BD}${Y}${UPPER:$wi:1}${RS}"',
    '  sleep 0.04',
    'done',
    '',
    '# Victory sparkles',
    'for ((vs=0;vs<25;vs++)); do',
    '  vx=$((RANDOM%COLS+1)); vy=$((RANDOM%LNS+1))',
    '  ((vy>=MY-2 && vy<=MY+2)) && continue',
    '  cur $vy $vx; out "${BD}${CL[$((RANDOM%7))]}*${RS}"',
    '  sleep 0.02',
    'done',
    'sleep 1.0; clear',
    '',
    '# ═══════════════════════════════════════════════════',
    '# STICK FIGURES IN CAP & GOWN DANCING',
    '# ═══════════════════════════════════════════════════',
    '',
    '# 4 stick figure dance frames (cap & gown, taller & more detailed)',
    '# Each frame is 10 lines tall with stage',
    'SF1=("   ___   " "   | |   " "   -+-   " "    O    " "   /|\\\\   " "  / | \\\\  " "    |    " "   / \\\\   " "  /   \\\\  " " _/     \\\\_")',
    'SF2=("   ___   " "   | |   " "   -+-   " "    O    " "  \\\\|    " "   \\\\|    " "    |    " "   / \\\\   " "  /   \\\\  " " _/     \\\\_")',
    'SF3=("   ___   " "   | |   " "   -+-   " "    O    " "   /|\\\\   " "  / | \\\\  " "    |    " "   _|_   " "  / | \\\\  " " _/ | \\\\_ ")',
    'SF4=("   ___   " "   | |   " "   -+-   " "    O    " "    |/   " "    |/   " "    |    " "   / \\\\   " "  /   \\\\  " " _/     \\\\_")',
    '',
    '# Place 5 figures across the screen',
    'FIG_W=10',
    'FIG_H=10',
    'NFIGS=5',
    'declare -a FIG_X',
    'for ((fi=0;fi<NFIGS;fi++)); do',
    '  FIG_X[$fi]=$(( (COLS/(NFIGS+1)) * (fi+1) - FIG_W/2 ))',
    'done',
    'FIG_Y=$(( MY - FIG_H/2 - 1 ))',
    '',
    '# Draw stage/dance floor line',
    'STAGE_Y=$((FIG_Y+FIG_H+1))',
    'cur $STAGE_Y 1',
    'for ((sx=1;sx<=COLS;sx++)); do',
    '  if ((sx%3==0)); then out "${BD}${Y}=${RS}"; else out "${BD}${BO}-${RS}"; fi',
    'done',
    '',
    '# Dance loop: 48 frames',
    'for ((df=0;df<48;df++)); do',
    '  frame=$((df%4))',
    '  for ((fi=0;fi<NFIGS;fi++)); do',
    '    ff=$(( (df+fi)%4 ))',
    '    case $ff in',
    '      0) CUR_F=("${SF1[@]}");;',
    '      1) CUR_F=("${SF2[@]}");;',
    '      2) CUR_F=("${SF3[@]}");;',
    '      3) CUR_F=("${SF4[@]}");;',
    '    esac',
    '    fc=${CL[$(( fi%7 ))]}',
    '    for ((sl=0;sl<FIG_H;sl++)); do',
    '      cur $((FIG_Y+sl)) ${FIG_X[$fi]}',
    '      out "          "',
    '      cur $((FIG_Y+sl)) ${FIG_X[$fi]}',
    '      if ((sl<3)); then',
    '        out "${BD}${Y}${CUR_F[$sl]}${RS}"',
    '      else',
    '        out "${BD}${fc}${CUR_F[$sl]}${RS}"',
    '      fi',
    '    done',
    '  done',
    '  sleep 0.10',
    'done',
    '',
    '# "CLASS OF 2026" text below stage',
    'WMI="* * *  C L A S S   O F   2 0 2 6  * * *"',
    'WMI_X=$(( (COLS-${#WMI})/2 ))',
    'cur $((STAGE_Y+2)) $WMI_X',
    'out "${BD}${Y}${WMI}${RS}"',
    'sleep 1.0; clear',
    '',
    '# ═══════════════════════════════════════════════════',
    '# PHASE 4: UT TOWER (ASCII art, drawn line by line in burnt orange)',
    '# ═══════════════════════════════════════════════════',
    'TOWER=(',
    '"                  .+.                  "',
    '"                 /|X|\\\\                 "',
    '"                /_|X|_\\\\                "',
    '"                | *** |                "',
    '"               _|_____|_               "',
    '"              |  _____  |              "',
    '"              | |     | |              "',
    '"              | | U T | |              "',
    '"              | |  _  | |              "',
    '"              | | |_| | |              "',
    '"              | |_____| |              "',
    '"         _____|_________|_____         "',
    '"        |  ___|         |___  |        "',
    '"        | |   | ||| ||| |   | |        "',
    '"        | |   | ||| ||| |   | |        "',
    '"        | |   | ||| ||| |   | |        "',
    '"        | |   | ||| ||| |   | |        "',
    '"        | |___|_________|___| |        "',
    '"        |_____________________|        "',
    '"        | | | | | | | | | | | |        "',
    '"        | | | | | | | | | | | |        "',
    '"        | | | | | | | | | | | |        "',
    '"        |_|_|_|_|_|_|_|_|_|_|_|        "',
    '"       /                       \\\\       "',
    '"      /  ~  ~  ~  TEXAS  ~  ~  \\\\      "',
    '"     /___________________________\\\\     "',
    '"    |_____________________________|    "',
    ')',
    'TW_H=${#TOWER[@]}',
    'TW_W=42',
    'TW_X=$(( (COLS-TW_W)/2 ))',
    'TW_Y=$(( (LNS-TW_H)/2 - 3 ))',
    '((TW_Y<1)) && TW_Y=1',
    '',
    '# Draw tower line by line with slight delay',
    'for ((ln=0;ln<TW_H;ln++)); do',
    '  cur $((TW_Y+ln)) $TW_X',
    '  out "${BD}${BO}${TOWER[$ln]}${RS}"',
    '  sleep 0.05',
    'done',
    '',
    '# Flash the star/beacon at top',
    'for ((fl=0;fl<8;fl++)); do',
    '  cur $((TW_Y)) $((TW_X+18))',
    '  if ((fl%3==0)); then out "${BD}${Y}.+.${RS}"',
    '  elif ((fl%3==1)); then out "${BD}${W}*+*${RS}"',
    '  else out "${BD}${BO}.+.${RS}"; fi',
    '  sleep 0.12',
    'done',
    '',
    '# Light up the windows one by one',
    'for ((wi=0;wi<6;wi++)); do',
    '  wy=$((TW_Y+13+wi/2))',
    '  wx=$((TW_X+14+(wi%2)*8))',
    '  cur $wy $wx; out "${BD}${Y}|||${RS}"',
    '  sleep 0.08',
    'done',
    '',
    '# "THE UNIVERSITY OF TEXAS AT AUSTIN" text below tower',
    'UT_TXT="THE UNIVERSITY OF TEXAS AT AUSTIN"',
    'UT_X=$(( (COLS-${#UT_TXT})/2 ))',
    'cur $((TW_Y+TW_H+1)) $UT_X',
    'for ((ti=0;ti<${#UT_TXT};ti++)); do',
    '  out "${BD}${BO}${UT_TXT:$ti:1}${RS}"',
    '  sleep 0.02',
    'done',
    '',
    '# Add "Est. 1883" below',
    'EST="Est. 1883"',
    'EST_X=$(( (COLS-${#EST})/2 ))',
    'cur $((TW_Y+TW_H+2)) $EST_X',
    'out "${DM}${W}${EST}${RS}"',
    'sleep 1.2; clear',
    '',
    '# ═══════════════════════════════════════════════════',
    '# PHASE 4.5: YELLOW BRICK ROAD — STORY ANIMATION',
    '# Person walks out of tower, yellow brick road, cap toss,',
    '# enters globe, rules the world',
    '# ═══════════════════════════════════════════════════',
    '',
    '# Scene 1: Person walks out of the UT Tower doors',
    '# Mini tower at top, person appears at base',
    'MINI_TOWER=(',
    '"       |___|       "',
    '"      |     |      "',
    '"      | U T |      "',
    '"   ___|_____|___   "',
    '"  |  ||| ||| ||  | "',
    '"  |  ||| ||| ||  | "',
    '"  |_______________|"',
    '"  |  | | | | | |  |"',
    '"  |__|_|_|_|_|_|__|"',
    '"  /               \\\\"',
    '" /_________________\\\\"',
    ')',
    'MT_H=${#MINI_TOWER[@]}',
    'MT_W=22',
    'MT_X=$(( (COLS-MT_W)/2 ))',
    'MT_Y=2',
    '',
    '# Draw mini tower',
    'for ((ln=0;ln<MT_H;ln++)); do',
    '  cur $((MT_Y+ln)) $MT_X',
    '  out "${BD}${BO}${MINI_TOWER[$ln]}${RS}"',
    '  sleep 0.03',
    'done',
    '',
    '# Person in cap & gown walks out of door',
    'DOOR_Y=$((MT_Y+MT_H))',
    'DOOR_X=$((MT_X+MT_W/2))',
    '',
    '# Grad figure frames (cap & gown)',
    'GRAD1=(" [=] " "  O  " " /|\\\\ " " / \\\\ ")',
    'GRAD2=(" [=] " "  O  " " /|\\\\ " "  |  " " / \\\\ ")',
    '',
    '# Walk person out of the tower and down',
    'for ((step=0;step<8;step++)); do',
    '  py=$((DOOR_Y+step))',
    '  px=$((DOOR_X-2))',
    '  # Clear previous position',
    '  ((step>0)) && {',
    '    for ((ci=0;ci<4;ci++)); do',
    '      cur $((py-1+ci-4)) $((px)); out "     "',
    '    done',
    '  }',
    '  # Draw grad figure',
    '  if ((step%2==0)); then',
    '    for ((gi=0;gi<4;gi++)); do',
    '      cur $((py+gi)) $px; out "${BD}${W}${GRAD1[$gi]}${RS}"',
    '    done',
    '  else',
    '    for ((gi=0;gi<5;gi++)); do',
    '      cur $((py+gi)) $px; out "${BD}${W}${GRAD2[$gi]}${RS}"',
    '    done',
    '  fi',
    '  sleep 0.12',
    'done',
    'sleep 0.3',
    '',
    '# Scene 2: Yellow brick road appears stretching to the right',
    'ROAD_Y=$((DOOR_Y+10))',
    'ROAD_START=$((DOOR_X-2))',
    '',
    '# Draw the yellow brick road extending across screen',
    'for ((bx=ROAD_START;bx<=COLS-2;bx+=3)); do',
    '  cur $((ROAD_Y)) $bx',
    '  out "${BD}${Y}[=]${RS}"',
    '  cur $((ROAD_Y+1)) $bx',
    '  out "${Y}[=]${RS}"',
    '  # sparkle on the road',
    '  ((RANDOM%3==0)) && {',
    '    cur $((ROAD_Y-1)) $bx; out "${BD}${Y}*${RS}"',
    '  }',
    '  sleep 0.02',
    'done',
    '',
    '# Walk person along the road',
    'for ((wx=ROAD_START;wx<=COLS-10;wx+=2)); do',
    '  # Clear previous',
    '  ((wx>ROAD_START)) && {',
    '    for ((ci=0;ci<5;ci++)); do',
    '      cur $((ROAD_Y-5+ci)) $((wx-2)); out "     "',
    '    done',
    '  }',
    '  # Draw walking grad',
    '  py=$((ROAD_Y-4))',
    '  if ((wx%4==0)); then',
    '    cur $py $wx;     out "${BD}${W} [=] ${RS}"',
    '    cur $((py+1)) $wx; out "${BD}${W}  O  ${RS}"',
    '    cur $((py+2)) $wx; out "${BD}${W} /|\\\\ ${RS}"',
    '    cur $((py+3)) $wx; out "${BD}${W} / \\\\ ${RS}"',
    '  else',
    '    cur $py $wx;     out "${BD}${W} [=] ${RS}"',
    '    cur $((py+1)) $wx; out "${BD}${W}  O  ${RS}"',
    '    cur $((py+2)) $wx; out "${BD}${W} /|\\\\ ${RS}"',
    '    cur $((py+3)) $wx; out "${BD}${W}  |  ${RS}"',
    '    cur $((py+4)) $wx; out "${BD}${W} / \\\\ ${RS}"',
    '  fi',
    '  sleep 0.03',
    'done',
    'sleep 0.3',
    '',
    '# Scene 3: Cap toss! Person throws cap in the air',
    'TOSS_X=$((COLS-10))',
    'TOSS_PY=$((ROAD_Y-4))',
    '',
    '# Clear the walking figure, draw standing figure without cap',
    'for ((ci=0;ci<5;ci++)); do',
    '  cur $((TOSS_PY+ci)) $TOSS_X; out "     "',
    'done',
    'cur $((TOSS_PY+1)) $TOSS_X; out "${BD}${W}  O  ${RS}"',
    'cur $((TOSS_PY+2)) $TOSS_X; out "${BD}${W}\\\\|/${RS}"',
    'cur $((TOSS_PY+3)) $TOSS_X; out "${BD}${W} / \\\\ ${RS}"',
    '',
    '# Cap flies up with trail',
    'for ((cy=TOSS_PY;cy>=2;cy-=1)); do',
    '  # clear old cap',
    '  cur $((cy+1)) $((TOSS_X)); out "     "',
    '  cur $cy $((TOSS_X)); out "${BD}${Y} [=] ${RS}"',
    '  # sparkle trail',
    '  cur $((cy+1)) $((TOSS_X+RANDOM%3)); out "${Y}*${RS}"',
    '  sleep 0.06',
    'done',
    '',
    '# Cap spins at the top',
    'CAP_SPIN=("[=]" "-=-" "=_=" "-+-" "[=]")',
    'for ((sp=0;sp<10;sp++)); do',
    '  cur 2 $((TOSS_X)); out "${BD}${Y} ${CAP_SPIN[$((sp%5))]} ${RS}"',
    '  sleep 0.08',
    'done',
    'sleep 0.3',
    '',
    '# Scene 4: Clear everything, earth/globe takes over the screen',
    'clear',
    '',
    '# Draw a big ASCII earth globe',
    'GLOBE=(',
    '"            .--------.            "',
    '"        .--~  ~   ~   ~--.        "',
    '"      /~  .  ~ ~  . ~  ~  ~\\\\     "',
    '"     / ~ .     ~   .  ~     \\\\    "',
    '"    / ~   ____  ~ .   ~ ~   \\\\   "',
    '"   | . ~ / .--\\\\ ~  ~ .   ~  |   "',
    '"   |~ . | |  ~ ||  ~ . ~ ~  |   "',
    '"   | .~ | |___||~  .   ~    |   "',
    '"   |  ~ \\\\  ---/ .  ~ . ~   |   "',
    '"    \\\\ ~  ----  ~   .  ~   /    "',
    '"     \\\\ . ~ ~  . ~ .  ~   /     "',
    '"      \\\\~  ~ .  ~  ~ .  ~/      "',
    '"        ~--..  ~ ..--~          "',
    '"            ~----~              "',
    ')',
    'GL_H=${#GLOBE[@]}',
    'GL_W=34',
    'GL_X=$(( (COLS-GL_W)/2 ))',
    'GL_Y=$(( (LNS-GL_H)/2 - 3 ))',
    '((GL_Y<1)) && GL_Y=1',
    '',
    '# Globe expand animation - start small, grow',
    'for ((ez=1;ez<=3;ez++)); do',
    '  clear',
    '  # Draw expanding circle of dots',
    '  for ((a=0;a<36;a++)); do',
    '    angle=$((a*10))',
    '    # approximate circle with random scatter',
    '    cx=$((MX + ez*3*(RANDOM%3-1) ))',
    '    cy=$((MY + ez*2*(RANDOM%3-1) ))',
    '    ((cx>0 && cx<=COLS && cy>0 && cy<=LNS)) && {',
    '      cur $cy $cx; out "${BD}${C}*${RS}"',
    '    }',
    '  done',
    '  sleep 0.08',
    'done',
    'clear',
    '',
    '# Draw the full globe',
    'for ((ln=0;ln<GL_H;ln++)); do',
    '  cur $((GL_Y+ln)) $GL_X',
    '  out "${BD}${C}${GLOBE[$ln]}${RS}"',
    '  sleep 0.04',
    'done',
    '',
    '# Add continents coloring - some lines in green',
    'for ((ln=4;ln<11;ln++)); do',
    '  cur $((GL_Y+ln)) $GL_X',
    '  out "${BD}${G}${GLOBE[$ln]}${RS}"',
    '  sleep 0.03',
    'done',
    'sleep 0.3',
    '',
    '# Person standing on top of globe (ruler of the world)',
    'RULER_Y=$((GL_Y-5))',
    'RULER_X=$((GL_X+GL_W/2-3))',
    'cur $((RULER_Y)) $RULER_X;   out "${BD}${Y}  \\\\|/${RS}"',
    'cur $((RULER_Y+1)) $RULER_X; out "${BD}${W}  O  ${RS}"',
    'cur $((RULER_Y+2)) $RULER_X; out "${BD}${W} /|\\\\ ${RS}"',
    'cur $((RULER_Y+3)) $RULER_X; out "${BD}${W} / \\\\ ${RS}"',
    'sleep 0.3',
    '',
    '# Crown appears above head',
    'for ((cf=0;cf<6;cf++)); do',
    '  cur $((RULER_Y-1)) $((RULER_X))',
    '  if ((cf%2==0)); then out "${BD}${Y} .-=+=-. ${RS}"; else out "${BD}${BO} .-=+=-. ${RS}"; fi',
    '  sleep 0.12',
    'done',
    '',
    '# Text: "$NAME RULES THE WORLD"',
    'RULES_TXT="$UPPER RULES THE WORLD"',
    'RULES_X=$(( (COLS-${#RULES_TXT})/2 ))',
    'cur $((GL_Y+GL_H+2)) $RULES_X',
    'for ((ri=0;ri<${#RULES_TXT};ri++)); do',
    '  out "${BD}${Y}${RULES_TXT:$ri:1}${RS}"',
    '  sleep 0.03',
    'done',
    'sleep 0.3',
    '',
    '# Sparkle around the globe',
    'for ((ss=0;ss<40;ss++)); do',
    '  sx=$((GL_X-5+RANDOM%(GL_W+10)))',
    '  sy=$((GL_Y-2+RANDOM%(GL_H+4)))',
    '  ((sy>0 && sy<=LNS && sx>0 && sx<=COLS)) && {',
    '    cur $sy $sx; out "${BD}${CL[$((RANDOM%7))]}*${RS}"',
    '  }',
    '  sleep 0.03',
    'done',
    '',
    '# Flash the title',
    'for ((ft=0;ft<4;ft++)); do',
    '  cur $((GL_Y+GL_H+2)) $RULES_X',
    '  out "${BD}${CL[$((RANDOM%7))]}${RULES_TXT}${RS}"',
    '  sleep 0.1',
    'done',
    'sleep 1.0; clear',
    '',
    '# ═══════════════════════════════════════════════════',
    '# PHASE 5: McCOMBS SCHOOL OF BUSINESS',
    '# ═══════════════════════════════════════════════════',
    'MCCOMBS=(',
    '"  __  __      ____                _          "',
    '" |  \\\\/  | ___/ ___|___  _ __ ___ | |__  ___  "',
    '" | |\\\\/| |/ __| |   / _ \\\\| \'_ \\` _ \\\\| \'_ \\\\/ __| "',
    '" | |  | | (__| |__| (_) | | | | | | |_) \\\\__ \\\\ "',
    '" |_|  |_|\\\\___|\\\\____\\\\___/|_| |_| |_|_.__/|___/ "',
    ')',
    'MC_H=${#MCCOMBS[@]}',
    'MC_W=${#MCCOMBS[0]}',
    'MC_X=$(( (COLS-MC_W)/2 ))',
    'MC_Y=$(( MY - MC_H/2 - 3 ))',
    '((MC_Y<1)) && MC_Y=1',
    '',
    '# Draw McCombs text with typewriter effect',
    'for ((ln=0;ln<MC_H;ln++)); do',
    '  cur $((MC_Y+ln)) $MC_X',
    '  out "${BD}${BO}${MCCOMBS[$ln]}${RS}"',
    '  sleep 0.1',
    'done',
    '',
    '# Subtitle',
    'SUB="SCHOOL OF BUSINESS"',
    'SUB_X=$(( (COLS-${#SUB})/2 ))',
    'cur $((MC_Y+MC_H+1)) $SUB_X',
    'out "${BD}${W}${SUB}${RS}"',
    'sleep 0.3',
    '',
    'SUB2="MASTER OF SCIENCE IN MARKETING"',
    'SUB2_X=$(( (COLS-${#SUB2})/2 ))',
    'cur $((MC_Y+MC_H+3)) $SUB2_X',
    '# typewriter effect for the degree name',
    'for ((ti=0;ti<${#SUB2};ti++)); do',
    '  out "${BD}${Y}${SUB2:$ti:1}${RS}"',
    '  sleep 0.03',
    'done',
    'sleep 0.4',
    '',
    'SUB3="Class of 2026"',
    'SUB3_X=$(( (COLS-${#SUB3})/2 ))',
    'cur $((MC_Y+MC_H+5)) $SUB3_X',
    'out "${BD}${M}${SUB3}${RS}"',
    'sleep 1.2; clear',
    '',
    '',
    '# ═══════════════════════════════════════════════════',
    '# PHASE 6.7: LONGHORN STAMPEDE HERD',
    '# ═══════════════════════════════════════════════════',
    '',
    '# --- Small longhorn (distant, running) ---',
    'LH_SM1=(" /\\\\_/\\\\ " "( o.o )" "/ > ^ <\\\\" "   | |  " "  _/ \\\\_ ")',
    'LH_SM2=(" /\\\\_/\\\\ " "( o.o )" "\\\\ > ^ </" "  | |   " " _/ \\\\_ ")',
    'LH_SM_H=5; LH_SM_W=9',
    '',
    '# --- Medium longhorn (detailed) ---',
    'LH_MD1=(',
    '"  ___/\\\\_________/\\\\___  "',
    '" /    o    .    o    \\\\ "',
    '"|       \\\\___/       |"',
    '" \\\\_   / \\\\   / \\\\   _/ "',
    '"   \\\\_/   \\\\_/   \\\\_/   "',
    ')',
    'LH_MD2=(',
    '"  ___/\\\\_________/\\\\___  "',
    '" /    o    .    o    \\\\ "',
    '"|       \\\\___/       |"',
    '" \\\\_  / \\\\   / \\\\   _/  "',
    '"   \\\\/   \\\\_/   \\\\_/    "',
    ')',
    'LH_MD_H=5; LH_MD_W=24',
    '',
    '# --- Large longhorn (closest, very detailed) ---',
    'LH_LG=(',
    '"  ____/\\\\___________________/\\\\____  "',
    '" /      O                O      \\\\ "',
    '"|          \\\\           /         |"',
    '"|           \\\\  _____  /          |"',
    '" \\\\           \\\\/     \\\\/           / "',
    '"  \\\\________________________________/  "',
    '"  |  / \\\\         / \\\\         / \\\\  | "',
    '"  | /   \\\\       /   \\\\       /   \\\\ | "',
    '"  |/     |     /     \\\\     |     \\\\| "',
    '"   |_____|    |_______|    |_____| "',
    ')',
    'LH_LG_H=10; LH_LG_W=40',
    '',
    '# Ground rumble effect before stampede',
    'for ((rumble=0;rumble<8;rumble++)); do',
    '  for ((rx=1;rx<=COLS;rx+=3)); do',
    '    ry=$((LNS-RANDOM%2))',
    '    cur $ry $rx; out "${DM}${BO}~${RS}"',
    '  done',
    '  sleep 0.06',
    'done',
    '',
    '# "STAMPEDE!" text flashes',
    'STAMP_TXT=">>> STAMPEDE! <<<"',
    'STAMP_X=$(( (COLS-${#STAMP_TXT})/2 ))',
    'for ((sf=0;sf<4;sf++)); do',
    '  cur $((MY)) $STAMP_X',
    '  out "${BD}${CL[$((RANDOM%7))]}${STAMP_TXT}${RS}"',
    '  sleep 0.08',
    'done',
    'clear',
    '',
    '# Wave 1: Herd of 7 tiny longhorns stampeding',
    'HERD_Y1=$((MY-8)); ((HERD_Y1<2)) && HERD_Y1=2',
    'for ((lx=-10;lx<=COLS+2;lx+=3)); do',
    '  for ((hi=0;hi<7;hi++)); do',
    '    hy=$((HERD_Y1 + (hi%3)*6 - 2))',
    '    hx=$((lx - hi*5))',
    '    ((hx<1)) && continue',
    '    # Alternate run frames',
    '    if ((lx%6<3)); then frame_arr=("${LH_SM1[@]}"); else frame_arr=("${LH_SM2[@]}"); fi',
    '    for ((ll=0;ll<LH_SM_H;ll++)); do',
    '      ((hy+ll>0 && hy+ll<=LNS && hx>0)) && {',
    '        cur $((hy+ll)) $hx; out "${DM}${BO}${frame_arr[$ll]}${RS}"',
    '      }',
    '    done',
    '    # Clear trail',
    '    ex=$((hx-3))',
    '    ((ex>0)) && {',
    '      for ((ll=0;ll<LH_SM_H;ll++)); do',
    '        ((hy+ll>0 && hy+ll<=LNS)) && { cur $((hy+ll)) $ex; out "   "; }',
    '      done',
    '    }',
    '    # Dust clouds behind',
    '    ((RANDOM%3==0 && hx>3)) && {',
    '      cur $((hy+LH_SM_H-1)) $((hx-2)); out "${DM}${W}*..${RS}"',
    '    }',
    '  done',
    '  sleep 0.012',
    'done',
    'sleep 0.1',
    '',
    '# Wave 2: 3 medium longhorns with dust trail',
    'HERD_Y2=$((MY-3))',
    'for ((lx=-24;lx<=COLS+2;lx+=2)); do',
    '  for ((hi=0;hi<3;hi++)); do',
    '    hy=$((HERD_Y2 + hi*7 - 4))',
    '    hx=$((lx - hi*10))',
    '    ((hx<1)) && continue',
    '    if ((lx%4<2)); then',
    '      for ((ll=0;ll<LH_MD_H;ll++)); do',
    '        ((hy+ll>0 && hy+ll<=LNS && hx>0 && hx+LH_MD_W<=COLS)) && {',
    '          cur $((hy+ll)) $hx; out "${BD}${BO}${LH_MD1[$ll]}${RS}"',
    '        }',
    '      done',
    '    else',
    '      for ((ll=0;ll<LH_MD_H;ll++)); do',
    '        ((hy+ll>0 && hy+ll<=LNS && hx>0 && hx+LH_MD_W<=COLS)) && {',
    '          cur $((hy+ll)) $hx; out "${BD}${BO}${LH_MD2[$ll]}${RS}"',
    '        }',
    '      done',
    '    fi',
    '    # Clear trail',
    '    ex=$((hx-2))',
    '    ((ex>0)) && {',
    '      for ((ll=0;ll<LH_MD_H;ll++)); do',
    '        ((hy+ll>0 && hy+ll<=LNS)) && { cur $((hy+ll)) $ex; out "  "; }',
    '      done',
    '    }',
    '  done',
    '  # Dust cloud particles',
    '  for dd in 1 2 3 4 5 6; do',
    '    dp=$((HERD_Y2+RANDOM%14)); dpp=$((lx-RANDOM%10-3))',
    '    ((dpp>0 && dp>0 && dp<=LNS)) && { cur $dp $dpp; out "${DM}${W}*${RS}"; }',
    '  done',
    '  sleep 0.015',
    'done',
    'sleep 0.1',
    '',
    '# Wave 3: 1 HUGE longhorn charges across — screen shakes',
    'HERD_Y3=$((MY - LH_LG_H/2))',
    'for ((lx=-LH_LG_W;lx<=COLS+2;lx+=2)); do',
    '  # Screen shake effect — offset the Y randomly',
    '  shake=$((RANDOM%3-1))',
    '  for ((ll=0;ll<LH_LG_H;ll++)); do',
    '    dy=$((HERD_Y3+ll+shake))',
    '    ((dy>0 && dy<=LNS && lx>0 && lx+LH_LG_W<=COLS)) && {',
    '      cur $dy $lx; out "${BD}${BO}${LH_LG[$ll]}${RS}"',
    '    }',
    '    ex=$((lx-2))',
    '    ((ex>0 && dy>0 && dy<=LNS)) && { cur $dy $ex; out "  "; }',
    '  done',
    '  # Intense dust cloud + ground crack behind',
    '  for dd in 1 2 3 4 5 6 7 8 9 10; do',
    '    dp=$((HERD_Y3-3+RANDOM%(LH_LG_H+6)+shake)); dpp=$((lx-RANDOM%15-3))',
    '    ((dpp>0 && dp>0 && dp<=LNS)) && {',
    '      cur $dp $dpp',
    '      out "${CL[$((RANDOM%7))]}${FW[$((RANDOM%${#FW[@]}))]}${RS}"',
    '    }',
    '  done',
    '  sleep 0.01',
    'done',
    'sleep 0.15',
    '',
    '# --- SCREEN BREAK ---',
    'BREAK_Y=$MY',
    'for ((bx=1;bx<=COLS;bx++)); do',
    '  cur $BREAK_Y $bx',
    '  bc=${CL[$((RANDOM%7))]}',
    '  case $((RANDOM%6)) in',
    '    0) out "${BD}${bc}/${RS}" ;;',
    '    1) out "${BD}${bc}\\\\${RS}" ;;',
    '    2) out "${BD}${bc}X${RS}" ;;',
    '    3) out "${BD}${bc}#${RS}" ;;',
    '    4) out "${BD}${bc}*${RS}" ;;',
    '    5) out "${BD}${bc}=${RS}" ;;',
    '  esac',
    'done',
    'sleep 0.08',
    '',
    '# Screen flash + crack',
    'for ((fl=0;fl<4;fl++)); do',
    '  for ((bx=1;bx<=COLS;bx+=3)); do',
    '    by=$((BREAK_Y+RANDOM%3-1))',
    '    ((by>0 && by<=LNS)) && {',
    '      cur $by $bx',
    '      if ((fl%2==0)); then out "${BD}${W}###${RS}"; else out "${BD}${BO}><>${RS}"; fi',
    '    }',
    '  done',
    '  sleep 0.03',
    'done',
    '',
    '# HOOK EM text appears in the crack',
    'HE_TXT="HOOK EM \\\\m/"',
    'HE_X=$(( (COLS-${#HE_TXT})/2 ))',
    'cur $BREAK_Y $HE_X',
    'out "${BD}${BO}${HE_TXT}${RS}"',
    'sleep 0.8; clear',
    '',
    '',
    '# ═══════════════════════════════════════════════════',
    '# PHASE 8: FIREWORKS (12 bursts with trails and expanding rings)',
    '# ═══════════════════════════════════════════════════',
    'TRAIL_CHARS=("|" ":" "." " ")',
    'for burst in 1 2 3 4 5 6 7 8 9 10 11 12; do',
    '  cx=$((RANDOM%(COLS-20)+10)); cy=$((RANDOM%(LNS-12)+5))',
    '  c1=${CL[$((RANDOM%7))]}; c2=${CL[$((RANDOM%7))]}',
    '  # Visible trail going UP with fading tail',
    '  for ((ty=LNS;ty>cy;ty-=1)); do',
    '    cur $ty $cx; out "${BD}${c1}|${RS}"',
    '    # Draw fading trail below',
    '    for ((tt=1;tt<=3;tt++)); do',
    '      ((ty+tt<=LNS)) && {',
    '        cur $((ty+tt)) $cx; out "${DM}${c1}${TRAIL_CHARS[$((tt-1))]}${RS}"',
    '      }',
    '    done',
    '    ((ty+4<=LNS)) && { cur $((ty+4)) $cx; out " "; }',
    '    sleep 0.008',
    '  done',
    '  # Clear the trail',
    '  for ((cl=cy;cl<=cy+4 && cl<=LNS;cl++)); do',
    '    cur $cl $cx; out " "',
    '  done',
    '  # Expanding circular burst',
    '  for r in 1 2 3 4 5 6 7 8 9 10; do',
    '    fc=${CL[$((RANDOM%7))]}',
    '    # Draw a ring at radius r using 16 angles',
    '    for ((a=0;a<16;a++)); do',
    '      case $((a%16)) in',
    '        0)  dx=0;  dy=-1;;',
    '        1)  dx=1;  dy=-1;;',
    '        2)  dx=2;  dy=-1;;',
    '        3)  dx=2;  dy=0;;',
    '        4)  dx=2;  dy=1;;',
    '        5)  dx=1;  dy=1;;',
    '        6)  dx=0;  dy=1;;',
    '        7)  dx=-1; dy=1;;',
    '        8)  dx=-2; dy=1;;',
    '        9)  dx=-2; dy=0;;',
    '        10) dx=-2; dy=-1;;',
    '        11) dx=-1; dy=-1;;',
    '        12) dx=1;  dy=0;;',
    '        13) dx=-1; dy=0;;',
    '        14) dx=2;  dy=-1;;',
    '        15) dx=-2; dy=1;;',
    '      esac',
    '      px=$((cx+dx*r)); py=$((cy+dy*r/2))',
    '      ((px>0 && px<=COLS && py>0 && py<=LNS)) || continue',
    '      cur $py $px; ch=${FW[$((RANDOM%${#FW[@]}))]}',
    '      if ((r>7)); then out "${DM}${c2}${ch}${RS}"',
    '      elif ((r>4)); then out "${c1}${ch}${RS}"',
    '      else out "${BD}${fc}${ch}${RS}"; fi',
    '    done',
    '    sleep 0.025',
    '  done',
    '  sleep 0.08; ((burst%4==0)) && clear',
    'done',
    'sleep 0.2; clear',
    '',
    '',
    '# ═══════════════════════════════════════════════════',
    '# PHASE 9: NAME SCRAMBLE → REVEAL (block letters)',
    '# ═══════════════════════════════════════════════════',
    '# Use first name only for block letters (fits better)',
    'FIRST=$(echo "$UPPER" | cut -d" " -f1)',
    'FW2=0',
    'for ((i=0;i<${#FIRST};i++)); do',
    '  w=$(font_width "${FIRST:$i:1}"); FW2=$((FW2+w+2))',
    'done',
    'FX=$(( (COLS-FW2)/2 )); ((FX<1)) && FX=1',
    '',
    '# scramble 50 frames - fast cycling for dramatic effect',
    'for ((f=0;f<50;f++)); do',
    '  fc=${CL[$((f%7))]}; cx=$FX',
    '  for ((i=0;i<${#FIRST};i++)); do',
    '    ch="${FIRST:$i:1}"',
    '    draw_letter "$ch" $cx "scramble" "$fc"',
    '    w=$(font_width "$ch"); cx=$((cx+w+2))',
    '  done',
    '  if ((f<20)); then sleep 0.02',
    '  elif ((f<35)); then sleep 0.03',
    '  else sleep 0.05; fi',
    'done',
    '',
    '# resolve left to right',
    'for ((r=0;r<${#FIRST};r++)); do',
    '  cx=$FX',
    '  for ((i=0;i<${#FIRST};i++)); do',
    '    ch="${FIRST:$i:1}"',
    '    if ((i<=r)); then',
    '      draw_letter "$ch" $cx "solid" "${CL[$((i%7))]}"',
    '    else',
    '      draw_letter "$ch" $cx "scramble" "${CL[$(((r+i)%7))]}"',
    '    fi',
    '    w=$(font_width "$ch"); cx=$((cx+w+2))',
    '  done',
    '  sleep 0.2',
    'done',
    '',
    '# Full name below block letters',
    'FN_X=$(( (COLS-${#NAME})/2 ))',
    'cur $((SY+6)) $FN_X',
    'out "${BD}${W}${NAME}${RS}"',
    'sleep 0.5',
    '',
    '# ═══════════════════════════════════════════════════',
    '# PHASE 10: CONFETTI RAIN',
    '# ═══════════════════════════════════════════════════',
    'NT=$((SY-1)); NB=$((SY+7))',
    'CF=(\'*\' \'+\' \'o\' \'~\' \'#\' \'=\' \'^\' \'!\' \'.\' \':\' \'@\' \'%\')',
    'for ((f=0;f<240;f++)); do',
    '  for p in 1 2 3 4 5 6 7 8 9 10 11 12; do',
    '    px=$((RANDOM%COLS+1)); py=$((RANDOM%LNS+1))',
    '    ((py>=NT && py<=NB)) && continue',
    '    cur $py $px; out "${BD}${CL[$((RANDOM%7))]}${CF[$((RANDOM%${#CF[@]}))]}${RS}"',
    '  done',
    '  if ((f%3==0)); then',
    '    cx=$FX',
    '    for ((i=0;i<${#FIRST};i++)); do',
    '      ch="${FIRST:$i:1}"',
    '      draw_letter "$ch" $cx "solid" "${CL[$(((f/3+i)%7))]}"',
    '      w=$(font_width "$ch"); cx=$((cx+w+2))',
    '    done',
    '  fi',
    '  sleep 0.04',
    'done',
    '',
    '# ═══════════════════════════════════════════════════',
    '# PHASE 11: GRADUATION CAP + TASSEL FLIP',
    '# ═══════════════════════════════════════════════════',
    'sleep 0.4; clear',
    '',
    'CAP=(',
    '"              ________________________              "',
    '"            /                          \\\\            "',
    '"          /                              \\\\          "',
    '"   ______/                                \\\\______   "',
    '"  /________________________________________________\\\\ "',
    '"  \\\\________________________________________________/ "',
    '"          |                          |               "',
    '"          |                          |               "',
    '"          |          ______          |               "',
    '"          |         |  ##  |         |               "',
    '"          |         | #### |         |               "',
    '"          |         |__##__|         |               "',
    '"          |            ##            |               "',
    '"          |            ##            |               "',
    '"          |           /##\\\\           |               "',
    '"          |          / ## \\\\          |               "',
    '"          |         /  ##  \\\\         |               "',
    '"          |        / ####  \\\\        |               "',
    '"          |_______/ ###### \\\\_______|               "',
    ')',
    'CAP_H=${#CAP[@]}',
    'CAP_W=${#CAP[0]}',
    'CAP_X=$(( (COLS-CAP_W)/2 ))',
    'CAP_Y=$(( (LNS-CAP_H)/2 - 4 ))',
    '((CAP_Y<1)) && CAP_Y=1',
    '',
    '# Draw cap line by line',
    'for ((ln=0;ln<CAP_H;ln++)); do',
    '  cur $((CAP_Y+ln)) $CAP_X',
    '  if ((ln<6)); then',
    '    out "${BD}${BO}${CAP[$ln]}${RS}"',
    '  else',
    '    out "${BD}${Y}${CAP[$ln]}${RS}"',
    '  fi',
    '  sleep 0.06',
    'done',
    'sleep 0.3',
    '',
    '# Tassel swing animation (6 frames, swings left to right)',
    'TASSEL_X=$((CAP_X + CAP_W/2 + 10))',
    'TASSEL_Y=$((CAP_Y + 4))',
    'T1=("   |  " "   |  " "   |  " "   *  " "  /|  " " / |  " "/  |  ")',
    'T2=("  |   " "  |   " "  |   " "  *   " "  |\\\\  " "  | \\\\ " "  |  \\\\")',
    'T3=("  |   " "   |  " "   |  " "   *  " "  /|\\\\ " " / | \\\\" "/  |  \\\\")',
    'T4=(" |    " " |    " " |    " " *    " "/|    " "| /   " "|/    ")',
    'T5=("    | " "    | " "    | " "    * " "    |\\\\" "    | \\\\" "    |/")',
    'T6=("  |   " "   |  " "   |  " "   *  " "  /|\\\\ " " / | \\\\" "/  |  \\\\")',
    '',
    'for swing in 1 2 3 4; do',
    '  for frame in 0 1 2 3 4 5 2 1; do',
    '    case $frame in',
    '      0) TF=("${T1[@]}");;',
    '      1) TF=("${T2[@]}");;',
    '      2) TF=("${T3[@]}");;',
    '      3) TF=("${T4[@]}");;',
    '      4) TF=("${T5[@]}");;',
    '      5) TF=("${T6[@]}");;',
    '    esac',
    '    for ((tl=0;tl<${#TF[@]};tl++)); do',
    '      cur $((TASSEL_Y+tl)) $TASSEL_X',
    '      out "       "',
    '      cur $((TASSEL_Y+tl)) $TASSEL_X',
    '      out "${BD}${BO}${TF[$tl]}${RS}"',
    '    done',
    '    sleep 0.07',
    '  done',
    'done',
    'sleep 0.5',
    '',
    '',
    '# ═══════════════════════════════════════════════════',
    '# PHASE 12.7: PERSONALIZED FLEX',
    '# ═══════════════════════════════════════════════════',
    '',
    '# Simple, elegant credential reveal',
    'MSGS=(',
    '  "$NAME"',
    '  ""',
    '  "MASTER OF SCIENCE"',
    '  "CLASS OF 2026"',
    '  ""',
    '  "McCOMBS SCHOOL OF BUSINESS"',
    '  "THE UNIVERSITY OF TEXAS AT AUSTIN"',
    ')',
    'MSG_Y=$((MY-5))',
    '',
    'for ((mi=0;mi<${#MSGS[@]};mi++)); do',
    '  msg="${MSGS[$mi]}"',
    '  if [ -z "$msg" ]; then continue; fi',
    '  msg_x=$(( (COLS-${#msg})/2 ))',
    '  ((msg_x<1)) && msg_x=1',
    '  cur $((MSG_Y+mi*2)) $msg_x',
    '  if ((mi==0)); then mc="${BD}${W}"',
    '  elif ((mi==2)); then mc="${BD}${Y}"',
    '  elif ((mi==3)); then mc="${BD}${BO}"',
    '  elif ((mi==5)); then mc="${BD}${BO}"',
    '  else mc="${DM}${W}"; fi',
    '  for ((ci=0;ci<${#msg};ci++)); do',
    '    out "${mc}${msg:$ci:1}${RS}"',
    '    sleep 0.02',
    '  done',
    '  sleep 0.4',
    'done',
    'sleep 1.2; clear',
    '',
    '',
    '',
    '# ═══════════════════════════════════════════════════',
    '# PHASE 13: "CONGRATS" BLOCK REVEAL',
    '# ═══════════════════════════════════════════════════',
    'clear',
    '',
    'GRAD_MSG="MASTER"',
    'GRAD_UPPER=$(echo "$GRAD_MSG" | tr \'[:lower:]\' \'[:upper:]\')',
    'GW=0',
    'for ((i=0;i<${#GRAD_UPPER};i++)); do',
    '  w=$(font_width "${GRAD_UPPER:$i:1}"); GW=$((GW+w+2))',
    'done',
    'GX=$(( (COLS-GW)/2 )); ((GX<1)) && GX=1',
    'GY=$(( LNS/2 - 6 ))',
    '',
    'for ((f=0;f<20;f++)); do',
    '  fc=${CL[$((f%7))]}; cx=$GX',
    '  for ((i=0;i<${#GRAD_UPPER};i++)); do',
    '    ch="${GRAD_UPPER:$i:1}"',
    '    draw_letter_at "$ch" $cx $GY "scramble" "$fc"',
    '    w=$(font_width "$ch"); cx=$((cx+w+2))',
    '  done',
    '  sleep 0.04',
    'done',
    'for ((r=0;r<${#GRAD_UPPER};r++)); do',
    '  cx=$GX',
    '  for ((i=0;i<${#GRAD_UPPER};i++)); do',
    '    ch="${GRAD_UPPER:$i:1}"',
    '    if ((i<=r)); then',
    '      draw_letter_at "$ch" $cx $GY "solid" "${CL[$((i%7))]}"',
    '    else',
    '      draw_letter_at "$ch" $cx $GY "scramble" "${CL[$(((r+i)%7))]}"',
    '    fi',
    '    w=$(font_width "$ch"); cx=$((cx+w+2))',
    '  done',
    '  sleep 0.12',
    'done',
    '',
    '# Name below MASTER',
    'sleep 0.3',
    'NM_LINE="$NAME"',
    'NM_X=$(( (COLS-${#NM_LINE})/2 ))',
    'cur $((GY+7)) $NM_X',
    'out "${BD}${W}${NM_LINE}${RS}"',
    'sleep 0.2',
    '',
    '# Degree line',
    'DEG_LINE="M.S. Marketing"',
    'DEG_X=$(( (COLS-${#DEG_LINE})/2 ))',
    'cur $((GY+8)) $DEG_X',
    'out "${BD}${Y}${DEG_LINE}${RS}"',
    'sleep 0.3',
    '',
    '# ═══════════════════════════════════════════════════',
    '# PHASE 14: HOOK EM — LONGHORN + \\m/',
    '# ═══════════════════════════════════════════════════',
    '',
    '# "HOOK EM" in block letters below congrats',
    'HOOK_MSG="HOOK EM"',
    'HW=0',
    'for ((i=0;i<${#HOOK_MSG};i++)); do',
    '  w=$(font_width "${HOOK_MSG:$i:1}"); HW=$((HW+w+2))',
    'done',
    'HX=$(( (COLS-HW)/2 )); ((HX<1)) && HX=1',
    'HY=$((GY+9))',
    '',
    '# Reveal HOOK EM',
    'for ((r=0;r<${#HOOK_MSG};r++)); do',
    '  cx=$HX',
    '  for ((i=0;i<${#HOOK_MSG};i++)); do',
    '    ch="${HOOK_MSG:$i:1}"',
    '    if ((i<=r)); then',
    '      draw_letter_at "$ch" $cx $HY "solid" "${BO}"',
    '    else',
    '      draw_letter_at "$ch" $cx $HY "scramble" "${CL[$(((r+i)%7))]}"',
    '    fi',
    '    w=$(font_width "$ch"); cx=$((cx+w+2))',
    '  done',
    '  sleep 0.1',
    'done',
    '',
    '# Longhorn ASCII art',
    'HORN_Y=$((HY+7))',
    'HORN=(',
    '"    \\\\m/    "',
    '"   _/ \\\\_   "',
    '"  / . . \\\\  "',
    '"  \\\\_____/  "',
    ')',
    'HORN_W=${#HORN[0]}',
    'HORN_X=$(( (COLS-HORN_W)/2 ))',
    'for ((hl=0;hl<${#HORN[@]};hl++)); do',
    '  cur $((HORN_Y+hl)) $HORN_X',
    '  out "${BD}${BO}${HORN[$hl]}${RS}"',
    '  sleep 0.08',
    'done',
    'sleep 0.5',
    '',
    '# ═══════════════════════════════════════════════════',
    '# PHASE 15: FINAL FIREWORKS + COLOR CYCLING',
    '# ═══════════════════════════════════════════════════',
    'for ((burst=0;burst<40;burst++)); do',
    '  for p in 1 2 3 4 5 6 7 8 9 10 11 12 13 14; do',
    '    px=$((RANDOM%COLS+1)); py=$((RANDOM%LNS+1))',
    '    ((py>=GY && py<=HORN_Y+5)) && continue',
    '    cur $py $px; out "${CL[$((RANDOM%7))]}${FW[$((RANDOM%${#FW[@]}))]}${RS}"',
    '  done',
    '  # cycle congrats + hook em colors',
    '  if ((burst%3==0)); then',
    '    cx=$GX',
    '    for ((i=0;i<${#GRAD_UPPER};i++)); do',
    '      ch="${GRAD_UPPER:$i:1}"',
    '      draw_letter_at "$ch" $cx $GY "solid" "${CL[$(((burst/3+i)%7))]}"',
    '      w=$(font_width "$ch"); cx=$((cx+w+2))',
    '    done',
    '    cx=$HX',
    '    for ((i=0;i<${#HOOK_MSG};i++)); do',
    '      ch="${HOOK_MSG:$i:1}"',
    '      draw_letter_at "$ch" $cx $HY "solid" "${CL[$(((burst/3+i+3)%7))]}"',
    '      w=$(font_width "$ch"); cx=$((cx+w+2))',
    '    done',
    '  fi',
    '  sleep 0.1',
    'done',
    '',
    '# ═══════════════════════════════════════════════════',
    '# PHASE 16: SCREEN CRACK + CHAOS FINALE',
    '# ═══════════════════════════════════════════════════',
    '# Screen "cracks" radiate from center',
    'crack_chars=("/" "\\\\" "|" "-" "+" "X" "*")',
    'for ((cr=1;cr<=25;cr++)); do',
    '  for angle in 0 1 2 3 4 5 6 7; do',
    '    case $angle in',
    '      0) cdx=0;  cdy=-1;;',
    '      1) cdx=1;  cdy=-1;;',
    '      2) cdx=2;  cdy=0;;',
    '      3) cdx=1;  cdy=1;;',
    '      4) cdx=0;  cdy=1;;',
    '      5) cdx=-1; cdy=1;;',
    '      6) cdx=-2; cdy=0;;',
    '      7) cdx=-1; cdy=-1;;',
    '    esac',
    '    cpx=$((MX + cdx*cr + RANDOM%3-1))',
    '    cpy=$((MY + cdy*cr))',
    '    ((cpx>0 && cpx<=COLS && cpy>0 && cpy<=LNS)) && {',
    '      cur $cpy $cpx',
    '      out "${BD}${CL[$((RANDOM%7))]}${crack_chars[$((RANDOM%${#crack_chars[@]}))]}${RS}"',
    '    }',
    '  done',
    '  sleep 0.04',
    'done',
    'sleep 0.3',
    '',
    '# Rapid color flash grand finale',
    'for ((ff=0;ff<8;ff++)); do',
    '  fc=${CL[$((ff%7))]}',
    '  cx=$GX',
    '  for ((i=0;i<${#GRAD_UPPER};i++)); do',
    '    ch="${GRAD_UPPER:$i:1}"',
    '    draw_letter_at "$ch" $cx $GY "solid" "$fc"',
    '    w=$(font_width "$ch"); cx=$((cx+w+2))',
    '  done',
    '  cx=$HX',
    '  for ((i=0;i<${#HOOK_MSG};i++)); do',
    '    ch="${HOOK_MSG:$i:1}"',
    '    draw_letter_at "$ch" $cx $HY "solid" "$fc"',
    '    w=$(font_width "$ch"); cx=$((cx+w+2))',
    '  done',
    '  sleep 0.06',
    'done',
    '',
    '# Final burst — fill screen with confetti',
    'for ((fb=0;fb<400;fb++)); do',
    '  px=$((RANDOM%COLS+1)); py=$((RANDOM%LNS+1))',
    '  cur $py $px; out "${BD}${CL[$((RANDOM%7))]}${CF[$((RANDOM%${#CF[@]}))]}${RS}"',
    'done',
    'sleep 0.3',
    '',
    '# Hold final frame',
    'sleep 5; cur $LNS 1; printf "\\n"',
    'tput cnorm; tput sgr0',
    'PARTY',
  ].join('\n');
}

export default function TerminalParty() {
  const [search, setSearch] = useState("");
  const [selected, setSelected] = useState(null);
  const [copied, setCopied] = useState(false);
  const [sparkles, setSparkles] = useState([]);

  const filtered = NAMES.filter(n =>
    n.toLowerCase().includes(search.toLowerCase())
  );

  useEffect(() => {
    const interval = setInterval(() => {
      setSparkles(prev => {
        const next = prev
          .map(s => ({ ...s, y: s.y + s.speed, opacity: s.opacity - 0.015 }))
          .filter(s => s.opacity > 0);
        if (Math.random() > 0.4) {
          next.push({
            id: Date.now() + Math.random(),
            x: Math.random() * 100, y: -2,
            char: ["*", "\u00B7", "\u2726", "\u00B0", "\u2022", "\u2605"][Math.floor(Math.random() * 6)],
            color: ACCENT_COLORS[Math.floor(Math.random() * ACCENT_COLORS.length)],
            speed: 0.3 + Math.random() * 0.5, opacity: 1,
          });
        }
        return next;
      });
    }, 60);
    return () => clearInterval(interval);
  }, []);

  const handleCopy = () => {
    if (!selected) return;
    navigator.clipboard.writeText(generateBashScript(selected)).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <div style={{
      minHeight: "100vh", background: "#0A0A0F", color: "#F0EDE6",
      fontFamily: "'Space Mono', monospace", position: "relative", overflow: "hidden",
    }}>
      {sparkles.map(s => (
        <div key={s.id} style={{
          position: "fixed", left: `${s.x}%`, top: `${s.y}%`,
          color: s.color, opacity: s.opacity, fontSize: "14px",
          pointerEvents: "none", zIndex: 0,
        }}>{s.char}</div>
      ))}

      <div style={{
        position: "fixed", inset: 0, zIndex: 1, pointerEvents: "none",
        background: `url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.04'/%3E%3C/svg%3E")`,
        opacity: 0.5,
      }} />

      <div style={{ position: "relative", zIndex: 2, maxWidth: 900, margin: "0 auto", padding: "48px 24px" }}>
        <div style={{ textAlign: "center", marginBottom: 48 }}>
          <h1 style={{
            fontFamily: "'Syne', sans-serif", fontWeight: 800,
            fontSize: "clamp(2.5rem, 8vw, 5rem)", lineHeight: 1,
            background: "linear-gradient(135deg, #FF6B6B, #FFE66D, #4ECDC4, #A78BFA, #FF477E)",
            WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent", marginBottom: 8,
          }}>TERMINAL PARTY</h1>
          <p style={{ fontSize: 14, color: "#888", letterSpacing: "0.15em", textTransform: "uppercase", marginBottom: 6 }}>
            find your name &middot; copy the script &middot; paste in terminal
          </p>
          <p style={{ fontSize: 12, color: "#555", maxWidth: 440, margin: "0 auto", lineHeight: 1.6 }}>
            stars &rarr; UT rain &rarr; hex flood &rarr; glitch storm &rarr;
            disco floor &rarr; R vs Python &rarr; dancing grads &rarr;
            tower &rarr; yellow brick road &rarr; McCombs &rarr;
            longhorn stampede &rarr; fireworks &rarr; name reveal &rarr;
            confetti &rarr; graduation cap &rarr; personalized flex &rarr;
            MASTER reveal &rarr; HOOK EM &rarr; screen crack finale.
            fullscreen mandatory. no exceptions.
          </p>
        </div>

        <div style={{ marginBottom: 32 }}>
          <input type="text" value={search}
            onChange={e => { setSearch(e.target.value); setSelected(null); }}
            placeholder="search names..."
            style={{
              width: "100%", padding: "14px 20px", background: "#151520",
              border: "1px solid #2A2A3A", borderRadius: 8, color: "#F0EDE6",
              fontFamily: "'Space Mono', monospace", fontSize: 14,
              outline: "none", boxSizing: "border-box",
            }}
          />
        </div>

        {!selected && (
          <div style={{
            display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(110px, 1fr))",
            gap: 10, marginBottom: 40,
          }}>
            {filtered.map((name, i) => (
              <button key={name} onClick={() => setSelected(name)}
                style={{
                  background: "#151520",
                  border: `1px solid ${ACCENT_COLORS[i % ACCENT_COLORS.length]}33`,
                  borderRadius: 6, padding: "14px 8px", cursor: "pointer",
                  fontFamily: "'Bebas Neue', sans-serif", fontSize: 22,
                  letterSpacing: "0.05em",
                  color: ACCENT_COLORS[i % ACCENT_COLORS.length],
                  transition: "all 0.2s",
                }}
                onMouseEnter={e => {
                  e.currentTarget.style.background = `${ACCENT_COLORS[i % ACCENT_COLORS.length]}15`;
                  e.currentTarget.style.borderColor = ACCENT_COLORS[i % ACCENT_COLORS.length];
                  e.currentTarget.style.transform = "translateY(-2px)";
                }}
                onMouseLeave={e => {
                  e.currentTarget.style.background = "#151520";
                  e.currentTarget.style.borderColor = `${ACCENT_COLORS[i % ACCENT_COLORS.length]}33`;
                  e.currentTarget.style.transform = "translateY(0)";
                }}
              >{name}</button>
            ))}
          </div>
        )}

        {filtered.length === 0 && !selected && (
          <p style={{ textAlign: "center", color: "#555", fontSize: 14 }}>no names match &ldquo;{search}&rdquo;</p>
        )}

        {selected && (
          <div style={{ animation: "fadeIn 0.3s ease" }}>
            <style>{`@keyframes fadeIn { from { opacity:0; transform:translateY(10px) } to { opacity:1; transform:translateY(0) } }`}</style>

            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 20 }}>
              <button onClick={() => setSelected(null)} style={{
                background: "none", border: "1px solid #333", color: "#888",
                padding: "8px 16px", borderRadius: 6, cursor: "pointer",
                fontFamily: "'Space Mono', monospace", fontSize: 12,
              }}>&larr; back</button>
              <h2 style={{
                fontFamily: "'Syne', sans-serif", fontWeight: 800, fontSize: 32,
                color: ACCENT_COLORS[NAMES.indexOf(selected) % ACCENT_COLORS.length],
              }}>{selected}</h2>
              <div style={{ width: 80 }} />
            </div>

            <div style={{
              background: "#151520", border: "1px solid #2A2A3A",
              borderRadius: 8, padding: 20, marginBottom: 16,
            }}>
              <p style={{ fontSize: 13, color: "#aaa", margin: 0, lineHeight: 1.7 }}>
                <span style={{ color: "#FFE66D" }}>1.</span> Copy the script below<br/>
                <span style={{ color: "#4ECDC4" }}>2.</span> Open Terminal and go <b style={{color:"#fff"}}>fullscreen</b><br/>
                <span style={{ color: "#A78BFA" }}>3.</span> Paste the whole thing and hit Enter<br/>
                <span style={{ color: "#FF477E" }}>4.</span> Enjoy the show (~90 seconds of chaos)
              </p>
            </div>

            <div style={{ background: "#0D0D14", border: "1px solid #2A2A3A", borderRadius: 8, overflow: "hidden" }}>
              <div style={{
                display: "flex", alignItems: "center", justifyContent: "space-between",
                padding: "10px 16px", borderBottom: "1px solid #1A1A2A",
              }}>
                <div style={{ display: "flex", gap: 6 }}>
                  <div style={{ width: 10, height: 10, borderRadius: "50%", background: "#FF5F57" }} />
                  <div style={{ width: 10, height: 10, borderRadius: "50%", background: "#FEBC2E" }} />
                  <div style={{ width: 10, height: 10, borderRadius: "50%", background: "#28C840" }} />
                </div>
                <span style={{ fontSize: 11, color: "#555" }}>bash</span>
              </div>
              <pre style={{
                padding: 16, margin: 0, overflow: "auto", maxHeight: 350,
                fontSize: 11, lineHeight: 1.5, color: "#8B8BA0",
                fontFamily: "'Space Mono', monospace",
              }}>{generateBashScript(selected)}</pre>
            </div>

            <button onClick={handleCopy} style={{
              width: "100%", marginTop: 16, padding: "16px",
              background: copied ? "linear-gradient(135deg, #06D6A0, #4ECDC4)" : "linear-gradient(135deg, #FF477E, #A78BFA)",
              border: "none", borderRadius: 8, color: "#fff",
              fontFamily: "'Bebas Neue', sans-serif", fontSize: 24,
              letterSpacing: "0.1em", cursor: "pointer", transition: "all 0.3s",
            }}>{copied ? "COPIED \u2713" : "COPY SCRIPT"}</button>
          </div>
        )}

        <div style={{
          textAlign: "center", marginTop: 48, fontSize: 11, color: "#333",
          letterSpacing: "0.15em", textTransform: "uppercase",
        }}>ms marketing &middot; mccombs &middot; class of 2026 &middot; trey c.</div>
      </div>
    </div>
  );
}
